### ISSUE TITLE
Design: Create a draft of the UI and the features we want

### ISSUE THREAD

**Issue by gdorsi** [gdorsi/musica#11]
We want to build an app to help music creatives to store and share their creation to recieve some feedback from their friends and collaborators.

Features that are a MUST for us:
- The app should be local-first [as per this definition](https://www.inkandswitch.com/local-first/)
- It should be possible to share a playlist and add comments to parts of the music timeline
- The library should be syncable on a personal server or computer

Desired features:
- Versioning of a song, with timeline diffs?
- P2P syncing

For the design let's go with [Figma](https://www.figma.com/), it's the most widley used, quite simple and collaborative.

**Comment by gdorsi** [comment]
Some initial sketches: https://www.figma.com/design/2UFVbubAUKE2egHJmjEPwq/MMusicAA?node-id=0-1&t=oPpn7SEB6O1UVXYH-0

**Comment by gdorsi** [comment]
We want to build an app to help music creatives to store and share their creation to recieve some feedback from their friends and collaborators.

Features that are a MUST for us:
- The app should be local-first [as per this definition](https://www.inkandswitch.com/local-first/)
- It should be possible to share a playlist and add comments to parts of the music timeline
- The library should be syncable on a personal server or computer

Desired features:
- Versioning of a song, with timeline diffs?
- P2P syncing

**Comment by paolodo** [comment]
My first design idea: https://www.figma.com/design/VXf3oJvX7Wh2VKNxV01Eep/MusicApp?node-id=0-1&t=yZP5rE38u5ltf4fH-1

**Comment by gdorsi** [comment]
Next steps:
- Implement the player UI (next/prev buttons)
- Sync the play button in the table row with the player
- Make the song informations editable (pictures, name)
